export default class ActionTypes {

    static GET_RATES = 'GET_RATES';
    static GET_RATES_FULFILLED = 'GET_RATES_FULFILLED';
    static GET_RATES_ERROR = 'GET_RATES_ERROR';

    static GET_ARCHIVED_RATES = 'GET_ARCHIVED_RATES';
    static GET_ARCHIVED_RATES_FULFILLED = 'GET_ARCHIVED_RATES_FULFILLED';
    static GET_ARCHIVED_RATES_ERROR = 'GET_ARCHIVED_RATES_ERROR';

    static SET_AMOUNT = 'SET_AMOUNT';
    static SET_CURRENCY = 'SET_CURRENCY';

}